name: Elixir CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      AUTH_USER: admin
      AUTH_PASS: admin
      CI: "true"
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.2'
      - run: mix deps.get
      - run: mix test
      - run: mix validate_urls
